graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    subscriptions:
      websocket:
        path: /ws/subscriptions
    asyncModeEnabled: true

graphiql:
  enabled: true
  mapping: /graphiql
  endpoint:
    subscriptions: /subscriptions
    graphql: /graphql


